name: gif comment
on:
  issues:
    types: [opened]
    
jobs:
  comment:
    if: github.event_name == 'issues'
    steps:
      - name: Add funny comment
        uses: Mart83/funny-comment-action@v2.1
        id: FunnyComment
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
          comment_type: 'gif'
